# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sales-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Check environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Available memory: $(free -h)"
          echo "CPU cores: $(nproc)"

      - name: Install dependencies
        run: |
          npm install --no-audit
          cd client && npm install --no-audit

      - name: Build React app
        run: |
          cd client
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          GENERATE_SOURCEMAP: false

      - name: Verify build
        run: |
          echo "=== Checking build directory ==="
          pwd
          ls -la
          echo "=== Checking client directory ==="
          ls -la client/
          echo "=== Checking for build directory ==="
          if [ -d "client/build" ]; then
            echo "✅ Build directory found"
            ls -la client/build/
            echo "=== Build files count ==="
            find client/build -type f | wc -l
          else
            echo "❌ Build directory not found - build failed"
            echo "=== Available directories in client/ ==="
            find client/ -type d -maxdepth 2
            exit 1
          fi

      - name: Copy build files
        run: |
          mkdir -p public
          if [ -d "client/build" ]; then
            cp -r client/build/* public/
          fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sales-agent'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_196A6E3A57CD4DDC9C3CFD845C233AA0 }}
          package: .