# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - sales-agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install backend dependencies
        run: npm install

      - name: Build React client and move to public/
        run: |
          npm install --prefix client
          npm run build --prefix client
          mkdir -p public
          cp -r client/build/* public/

      - name: Create clean deployment zip
        run: |
          zip -r deploy.zip . -x "client/*" ".git/*" "node_modules/*" "*.log" "temp_audio/*" "conversation_history/*"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sales-agent'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_196A6E3A57CD4DDC9C3CFD845C233AA0 }}
          package: deploy.zip
        env:
          WEBSITE_NODE_DEFAULT_VERSION: '18.17.0'
          SCM_DO_BUILD_DURING_DEPLOYMENT: 'true'
          ENABLE_ORYX_BUILD: 'true'
          ORYX_PLATFORM: 'nodejs'